### ISSUE TITLE
After switching tools, the default values of parameters cannot be correctly read.

### ISSUE THREAD

**Issue by yvonneyoung-713** [Bio-OS/bio-mate#11]
After switching tools, the default values of parameters cannot be correctly read. The parameter value always comes from the first tool that runs in the cell.
![p1](https://github.com/Bio-OS/bio-mate/assets/152266961/192fd1e8-b588-4826-9ade-ff35264b80cb)
![image](https://github.com/Bio-OS/bio-mate/assets/152266961/14b5a163-d17f-4a33-8f78-b245441a0a8f)

**Comment by yulitao-byte** [comment]
0.3.1 已修复，https://test.pypi.org/project/bio-mate/0.3.1/#description 用这个测试下
